openapi: 3.0.0
info:
  title: reviewcenter
  version: '1.0'
  description: Insights on Steam game reviews.
servers:
  - url: 'http://localhost:5000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    delete:
      summary: Delete user account
      operationId: delete-user
      responses:
        '200':
          description: OK
      description: Delete an existing user.
    put:
      summary: Update user info
      operationId: put-user
      responses:
        '200':
          description: Information updated.
      description: Updates information about an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
  /api/reviewcenter/v1/reviews:
    get:
      summary: All reviews
      tags: []
      responses: {}
      operationId: get-v1-reviews
      description: Returns a list of reviews for every game available on Steam.
    parameters: []
  /api/reviewcenter/v1/reviews/id_1:
    get:
      summary: All reviews for a specific game
      tags: []
      responses: {}
      operationId: get-api-reviewcenter-v1-reviews-id_1
      description: Shows reviews for the game with id 1.
  /api/reviewcenter/v1/topgames:
    get:
      summary: Top games
      tags: []
      responses: {}
      operationId: get-api-reviewcenter-v1-reviews-top
      description: 'Returns a list of the better-reviewed 100 games, grouped by genre.'
    parameters: []
  /api/reviewcenter/v1/recommendation:
    get:
      summary: Game recommendations
      tags: []
      responses:
        '200':
          description: Recommendations are ready.
      operationId: get-api-reviewcenter-v1-gamerecommendation
      description: 'Returns a list of possible games for the user to try, based on their favorite games.'
    parameters: []
  /api/reviewcenter/v1/hiddengems:
    get:
      summary: Hidden gems
      tags: []
      responses: {}
      operationId: get-api-reviewcenter-v1-hiddengems
      description: Returns a list of games with a low number of highly-positive reviews.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes: {}
tags:
  - name: games
  - name: reviews
